<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

	  <Content Include="assets\**" CopyToOutputDirectory="Always" />
  </ItemGroup>


  <ItemGroup>
    <None Remove="assets\globalization\tr.json" />
    <None Remove="assets\globalization\uk.json" />
  </ItemGroup>

</Project>
