<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta14" />
		<PackageReference Include="Dynastio.Net" Version="2.1.1" />
		<Content Include="assets\**" CopyToOutputDirectory="PreserveNewest" />

	</ItemGroup>


</Project>
