<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <ApplicationIcon>assets\logo.ico</ApplicationIcon>
    <StartupObject></StartupObject>
    <Copyright>Halun™️ - Jalal Jaleh 2020</Copyright>
    <PackageProjectUrl>https://github.com/jalaljaleh/Dynastio.Bot</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jalaljaleh/Dynastio.Bot</RepositoryUrl>
    <NeutralLanguage>en</NeutralLanguage>
    <AssemblyVersion></AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>




  <ItemGroup>
	  <PackageReference Include="Discord.Net" Version="3.18.0" />
	  <PackageReference Include="Dynastio.Net" Version="2.1.4.1" />
	  <PackageReference Include="Google.Apis.YouTube.v3" Version="1.67.0.3343" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
	  <PackageReference Include="Telegram.Bot" Version="22.7.2" />
	  
	  <ProjectReference Include="..\Dynastio.Bot.Database\Dynastio.Bot.Database.csproj" />
       <ProjectReference Include="..\Dynastio.Bot.Global\Dynastio.Bot.Global.csproj" />
       <ProjectReference Include="..\Dynastio.Extenstions\Dynastio.Extenstions.csproj" />
       <ProjectReference Include="..\Dynastio.Graphic\Dynastio.Graphic.csproj" />
       <ProjectReference Include="..\Dynastio.Support.Bot\Dynastio.Support.Bot.csproj" />
 
  </ItemGroup>


	
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\GlobalizationService\Globally\GloballyLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GloballyLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\GlobalizationService\InteractionCommands\InetactionCommandsLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>InetactionCommandsLocale.resx</DependentUpon>
    </Compile>
  </ItemGroup>

	
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\GlobalizationService\Globally\GloballyLocale.ru.resx">
      <LastGenOutput>GloballyLocale.ru.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\GlobalizationService\Globally\GloballyLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>GloballyLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
	  
    <EmbeddedResource Update="Services\GlobalizationService\InteractionCommands\InetactionCommandsLocale.ru.resx">
      <LastGenOutput>CommandLocales.ru.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\GlobalizationService\InteractionCommands\InetactionCommandsLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>InetactionCommandsLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


	<ItemGroup>
		<Content Include="assets\**" CopyToOutputDirectory="PreserveNewest" />

	</ItemGroup>


	<ItemGroup>
	  <None Include="Interactions\Modules.Menu\Buttons\ButtonShapeGeneratorModule.cs" />
	</ItemGroup>
	
</Project>
