//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynastio.Bot.Services.GlobalizationService.Globally {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GloballyLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GloballyLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynastio.Bot.Services.GlobalizationService.Globally.GloballyLocale", typeof(GloballyLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found in my command modules sir !.
        /// </summary>
        public static string error_interactions_hanlder_unknown {
            get {
                return ResourceManager.GetString("error.interactions.hanlder.unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string menu_closed_description {
            get {
                return ResourceManager.GetString("menu.closed.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string menu_closed_title {
            get {
                return ResourceManager.GetString("menu.closed.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///### Your ranking **Level** is {level} and your **Xp** is {xp}.
        /// .
        /// </summary>
        public static string rank_embed_description {
            get {
                return ResourceManager.GetString("rank.embed.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {level}.
        /// </summary>
        public static string rank_embed_title {
            get {
                return ResourceManager.GetString("rank.embed.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank represents a user’s level within the XP Ranking System. As members send messages they earn XP, and accumulating enough XP advances their rank. Ranks are displayed in a leaderboard and can unlock role rewards at milestone levels. Explore the full documentation for the XP Ranking System : \n **[Read More .. Full Doucument](https://github.com/jalaljaleh/Dynastio.Bot/blob/master/Dynastio.Bot/Services/XpRankingSystem/XpRankingSystemService.md)**.
        /// </summary>
        public static string rank_help_embed_description {
            get {
                return ResourceManager.GetString("rank-help.embed.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynast.io Bot XP Ranking System.
        /// </summary>
        public static string rank_help_embed_title {
            get {
                return ResourceManager.GetString("rank-help.embed.title", resourceCulture);
            }
        }
    }
}
