//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynastio.Bot.Services.GlobalizationService.Globally {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GloballyLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GloballyLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynastio.Bot.Services.GlobalizationService.Globally.GloballyLocale", typeof(GloballyLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Set !.
        /// </summary>
        public static string all_set {
            get {
                return ResourceManager.GetString("all_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Syncer.
        /// </summary>
        public static string badge_syncer {
            get {
                return ResourceManager.GetString("badge_syncer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Not Found.
        /// </summary>
        public static string button_not_found {
            get {
                return ResourceManager.GetString("button.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Reward.
        /// </summary>
        public static string buttons_interactions_guildsetuprankingmodule_gamereward_label {
            get {
                return ResourceManager.GetString("buttons.interactions.guildsetuprankingmodule.gamereward.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string buttons_interactions_guildsetuprankingmodule_roleassignment_disable_label {
            get {
                return ResourceManager.GetString("buttons.interactions.guildsetuprankingmodule.roleassignment.disable.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string buttons_interactions_guildsetuprankingmodule_roleassignment_enable_label {
            get {
                return ResourceManager.GetString("buttons.interactions.guildsetuprankingmodule.roleassignment.enable.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string buttons_interactions_menu_close_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.close.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string buttons_interactions_menu_login_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.login.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string buttons_interactions_menu_logout_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.logout.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string buttons_interactions_menu_menu_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.menu.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string buttons_interactions_menu_players_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.players.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Chest.
        /// </summary>
        public static string buttons_interactions_menu_privatechest_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.privatechest.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string buttons_interactions_menu_profile_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.profile.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string buttons_interactions_menu_rank_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.rank.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Search Players.
        /// </summary>
        public static string buttons_interactions_menu_searchPlayers_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.searchPlayers.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string buttons_interactions_menu_servers_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.servers.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Badges.
        /// </summary>
        public static string buttons_interactions_menu_syncBadges_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.syncBadges.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Roles.
        /// </summary>
        public static string buttons_interactions_menu_syncRankRoles_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.syncRankRoles.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string buttons_interactions_menu_teams_label {
            get {
                return ResourceManager.GetString("buttons.interactions.menu.teams.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Prefix.
        /// </summary>
        public static string change_prefix {
            get {
                return ResourceManager.GetString("change_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Module.
        /// </summary>
        public static string enable_module {
            get {
                return ResourceManager.GetString("enable_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enabled.
        /// </summary>
        public static string not_enabled {
            get {
                return ResourceManager.GetString("not_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Modul.
        /// </summary>
        public static string ranking_module {
            get {
                return ResourceManager.GetString("ranking_module", resourceCulture);
            }
        }
    }
}
