<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dynastio.Bot.Global\Dynastio.Bot.Global.csproj" />
    <ProjectReference Include="..\Dynastio.Net\Dynastio.Net.csproj" />
  </ItemGroup>

</Project>
